### ISSUE TITLE
Security token expires after 1 hour

### ISSUE THREAD

**Issue by grosser** [miasma-rb/miasma-aws#55]
still same [issue](https://github.com/miasma-rb/miasma-aws/issues/51) after bumping to v0.3.20

```
[22:01:50] sfn update foo -f sparkleformation/foo.rb --defaults --yes
[22:04:19] [WARN]: Task failed (Miasma::Error::ApiError::RequestError: Bad Request) - Retry in 5 seconds [Attempt 1/20]
[23:01:59] ERROR: Miasma::Error::ApiError::RequestError: Forbidden - ExpiredToken: The security token included in the request is expired
[23:01:59] gems/miasma-0.3.4/lib/miasma/types/api.rb:126:in `block in request'
[23:01:59] gems/bogo-0.2.12/lib/bogo/retry.rb:65:in `run!'
[23:01:59] gems/miasma-0.3.4/lib/miasma/types/api.rb:148:in `retryable_request'
[23:01:59] gems/miasma-0.3.4/lib/miasma/types/api.rb:123:in `request'
[23:01:59] gems/miasma-aws-0.3.20/lib/miasma/contrib/aws/orchestration.rb:550:in `block in resource_all'
```

@chrisroberts

**Comment by grosser** [comment]
I'm thinking it should be >5 mins instead of 15s since that's the retry backoff ...

**Comment by grosser** [comment]
also the 15 should be a constant and not a copy-pasted number

**Comment by chrisroberts** [comment]
Yeah, the backoff makes sense that it would still be causing the issue. Since default expiry is one hour, I'll update the timeout to be 10 minutes.

**Comment by grosser** [comment]
thx, I'll give that a try!
need a release tho :)
